
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
    
    

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    # commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccountdanita753'
    backendAzureRmContainerName: 'storageaccountdanita753container'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: false
    
# - task: TerraformCLI@0
#   inputs:
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
#     environmentServiceName: 'azure-resource-manager-connection'
#     commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
#     allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    commandOptions: '-lock=false'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resource-manager-connection'
    allowTelemetryCollection: false



